# Generated by Django 3.1.2 on 2020-10-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtime',
            name='run_time',
            field=models.CharField(max_length=5),
        ),
    ]
