# Generated by Django 3.1.2 on 2020-10-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201021_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runtime',
            name='complete',
        ),
    ]
