# Generated by Django 3.1.2 on 2020-10-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_runtime_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
