# Generated by Django 3.1.2 on 2020-10-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_runtime_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtime',
            name='run_time',
            field=models.FloatField(),
        ),
    ]
