# Generated by Django 3.1.2 on 2020-10-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201021_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtime',
            name='created',
            field=models.DateField(),
        ),
    ]
