# Generated by Django 3.1.2 on 2020-10-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201022_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runtime',
            name='created',
        ),
    ]
