# Generated by Django 3.1.2 on 2020-11-09 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201108_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pints',
            name='pint_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 19, 2, 11, 832032, tzinfo=utc)),
        ),
    ]
