# Generated by Django 3.1.2 on 2020-11-09 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201109_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pints',
            name='pint_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 19, 43, 43, 416086, tzinfo=utc)),
        ),
    ]
