# Generated by Django 3.1.2 on 2020-11-09 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201109_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pints',
            name='pint_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 19, 53, 25, 946285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 19, 53, 25, 946285, tzinfo=utc)),
        ),
    ]
