# Generated by Django 3.1.2 on 2020-11-09 20:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_auto_20201109_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pints',
            name='pint_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 20, 20, 57, 391642, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 20, 20, 57, 391642, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='nickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nickname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
