# Generated by Django 3.1.2 on 2020-11-09 20:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201109_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pints',
            name='pint_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 20, 39, 8, 605638, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 20, 39, 8, 604608, tzinfo=utc)),
        ),
    ]
