# Generated by Django 3.1.2 on 2020-11-10 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201109_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runtime',
            name='date_time',
        ),
        migrations.AddField(
            model_name='runtime',
            name='date',
            field=models.DateField(default=datetime.date(2020, 11, 10)),
        ),
        migrations.AlterField(
            model_name='pints',
            name='pint_date',
            field=models.DateField(default=datetime.date(2020, 11, 10)),
        ),
    ]
