# Generated by Django 3.1.2 on 2020-11-19 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201110_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pints',
            name='pint_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
