# Generated by Django 3.1.2 on 2020-11-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201119_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pints',
        ),
    ]
